export const LOAD_MESSAGES_REQUEST = 'LOAD_MESSAGES_REQUEST';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FALSY = 'LOAD_MESSAGES_FALSY';

export const UPDATE_MESSAGE_REQUEST = 'UPDATE_MESSAGE_REQUEST';
export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';
export const UPDATE_MESSAGE_FALSY = 'UPDATE_MESSAGE_FALSY';

export const CHANGE_STATUS_MESSAGES_REQUEST = 'CHANGE_STATUS_MESSAGES_REQUEST';
export const CHANGE_STATUS_MESSAGES_SUCCESS = 'CHANGE_STATUS_MESSAGES_SUCCESS';
export const CHANGE_STATUS_MESSAGES_FALSY = 'CHANGE_STATUS_MESSAGES_FALSY';
