export const OPEN_NEW_MESSAGES_PORTAL = 'OPEN_NEW_MESSAGES_PORTAL';
export const CLOSE_NEW_MESSAGES_PORTAL = 'CLOSE_NEW_MESSAGES_PORTAL';

export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FALSY = 'SEND_EMAIL_FALSY';
